import {NextResponse} from 'next/server';import {getSupabaseAdmin} from '@/lib/supabase-admin';import {RESEARCH_SOURCES} from '@/lib/research-sources';
const TYPES=['county_property','deed_chain','mortgages','assignments_releases','judgments','state_tax_liens','federal_tax_liens','municipal_tax_water_sewer','hoa_condo','bankruptcy','occupancy','valuation','comparables'];
export async function POST(_:Request,{params}:{params:Promise<{id:string}>}){try{const {id}=await params,db=getSupabaseAdmin();const pq=await db.from('properties').select('*').eq('id',id).single();if(pq.error)throw pq.error;const p=pq.data;
const run=await db.from('analysis_runs').insert({property_id:id,run_type:'full_due_diligence',status:'running',summary:{property:p.address,parcel:p.parcel_number,owner:p.owner_name}}).select('id').single();
for(const type of TYPES){const relevant=RESEARCH_SOURCES.filter(s=>(s.kind===type||(['mortgages','assignments_releases'].includes(type)&&s.kind==='deed_chain'))&&(!s.counties||s.counties.includes(p.county)));const result={message:relevant.length?'Verification sources queued. Missing data is not treated as clear title.':'Provider/manual verification required.',sources:relevant.map(s=>({provider:s.label,url:s.url,automated:s.automated,note:s.note}))};const old=await db.from('due_diligence_checks').select('id').eq('property_id',id).eq('check_type',type).maybeSingle();const row={property_id:id,check_type:type,status:'pending',result,source:relevant.map(x=>x.label).join(', ')||'manual/provider',checked_at:null};old.data?await db.from('due_diligence_checks').update(row).eq('id',old.data.id):await db.from('due_diligence_checks').insert(row);
for(const s of relevant){const exists=await db.from('research_tasks').select('id').eq('property_id',id).eq('task_type',type).eq('provider',s.key).in('status',['pending','running']).maybeSingle();if(!exists.data)await db.from('research_tasks').insert({property_id:id,task_type:type,provider:s.key,status:s.automated?'pending':'manual_review_required',result:{url:s.url,label:s.label,note:s.note}})}}

// Commercial live-data tasks: these execute only when credentials are configured.
for(const type of ['county_property','valuation','comparables','mortgages']){const ex=await db.from('research_tasks').select('id').eq('property_id',id).eq('task_type',type).eq('provider','attom').in('status',['pending','running']).maybeSingle();if(!ex.data)await db.from('research_tasks').insert({property_id:id,task_type:type,provider:'attom',status:'pending',result:{label:'ATTOM Property API',note:'Live licensed property/AVM/comps/mortgage intelligence'}})}
await db.from('analysis_runs').update({status:'complete',completed_at:new Date().toISOString(),summary:{checks:TYPES.length,verified:0,pending:TYPES.length,note:'Research plan created; no source is marked clear without evidence.'}}).eq('id',run.data?.id);
return NextResponse.json({ok:true,checks:TYPES.length,property:{address:p.address,parcel:p.parcel_number,owner:p.owner_name,county:p.county}})}catch(e:any){return NextResponse.json({error:e.message},{status:500})}}
