'use client';
import {useEffect,useMemo,useState} from 'react';
import Nav from './Nav';
import {Bell,Search,TrendingUp,TriangleAlert,RefreshCw,MapPin,CalendarDays,ExternalLink} from 'lucide-react';

type Row={id:string;sheriff_number:string;sale_date:string|null;opening_bid:number|null;status:string;source_url:string;plaintiff:string;defendant:string;properties:any};
const fmt=(d:string|null)=>d?new Date(d).toLocaleString('en-US',{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}):'Date pending';
export default function Dashboard(){
 const [rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[scanning,setScanning]=useState(false),[msg,setMsg]=useState('');
 const [q,setQ]=useState('');
 async function load(){setLoading(true);try{const r=await fetch('/api/properties',{cache:'no-store'});const j=await r.json();setRows(j.data||[]);if(j.error)setMsg(j.error)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function scan(){setScanning(true);setMsg('Scanning CivilView for Delaware auctions…');try{const r=await fetch('/api/scan-auctions',{method:'POST'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Scan failed');setMsg(`Scan complete: ${j.found} listings found · ${j.newProperties} new properties.${j.errors?.length?' '+j.errors.join(' | '):''}`);await load()}catch(e:any){setMsg(e.message)}finally{setScanning(false)}}
 const filtered=useMemo(()=>rows.filter(r=>{const p=r.properties||{};return `${p.address} ${p.parcel_number} ${p.owner_name} ${r.sheriff_number} ${r.plaintiff}`.toLowerCase().includes(q.toLowerCase())}),[rows,q]);
 const counties=new Set(rows.map(r=>r.properties?.county).filter(Boolean)).size;
 return <main><Nav/><section className="content"><header><div><p className="eyebrow">DELAWARE / LIVE AUCTION RADAR</p><h1>Investment Command Center</h1><p className="subtitle">Discover sheriff sales first. Title, liens, valuation and bid analysis are added in the next diligence stages.</p></div><div className="headerActions"><button className="iconBtn"><Bell size={18}/></button><button className="primary" onClick={scan} disabled={scanning}><RefreshCw size={17} className={scanning?'spin':''}/> {scanning?'Scanning…':'Scan Auctions'}</button></div></header>
 <div className="search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search address, parcel, owner, plaintiff or sheriff number..."/><button disabled>Run Due Diligence</button></div>
 {msg&&<div className="scanMessage">{msg}</div>}
 <div className="stats"><div className="stat"><span>Tracked auctions</span><strong>{rows.length}</strong><small>{loading?'Loading…':'Live database'}</small></div><div className="stat"><span>Counties represented</span><strong>{counties}</strong><small className="good">New Castle · Kent · Sussex</small></div><div className="stat"><span>Title analysis</span><strong>Stage 2</strong><small>Not inferred from auction feed</small></div><div className="stat"><span>Unresolved title flags</span><strong>—</strong><small className="warn">Deep diligence not run yet</small></div></div>
 <div className="sectionHead"><div><h2>Delaware auction feed</h2><p>CivilView discovery records. Values and title conclusions are intentionally not invented.</p></div><button className="secondary" onClick={scan}><TrendingUp size={16}/> Refresh feed</button></div>
 <div className="grid">{filtered.map(r=>{const p=r.properties||{};return <div className="propertyCard" key={r.id}><div className="cardTop"><span className="pill medium">{(r.status||'scheduled').toUpperCase()}</span><span className="county">{p.county||'Delaware'}</span></div><h3>{p.address||'Address pending'}</h3><p className="muted"><MapPin size={14}/> {p.city||'Delaware'}, Delaware</p><div className="metrics"><div><span>Sheriff #</span><b>{r.sheriff_number||'—'}</b></div><div><span>Parcel</span><b>{p.parcel_number||'Not listed'}</b></div><div><span>Opening bid</span><b className="accent">{r.opening_bid?'$'+Number(r.opening_bid).toLocaleString():'Not published'}</b></div></div><div className="risk"><TriangleAlert size={16}/><span>Title not analyzed yet · plaintiff: {r.plaintiff||'not listed'}</span></div><div className="cardFoot"><span><CalendarDays size={15}/> {fmt(r.sale_date)}</span>{r.source_url&&<a href={r.source_url} target="_blank" rel="noreferrer">CivilView <ExternalLink size={13}/></a>}</div></div>})}</div>
 {!loading&&!filtered.length&&<div className="notice"><TriangleAlert/><div><b>No live auctions stored yet.</b><p>Press Scan Auctions. The scanner will query Delaware CivilView listings and save discovered records to Supabase.</p></div></div>}
 <div className="notice"><TriangleAlert/><div><b>Auction discovery is not title due diligence.</b><p>CivilView itself describes its listings as general summary information. Mortgage balances, surviving liens, judgments, taxes and title priority will only appear after their supporting sources are checked.</p></div></div></section></main>
}
