'use client';import {useEffect,useMemo,useState} from 'react';import Nav from './Nav';import {Bell,Search,TrendingUp,TriangleAlert,RefreshCw,MapPin,CalendarDays,ExternalLink,ShieldCheck} from 'lucide-react';
type A=any;const fmt=(d:any)=>d?new Date(d).toLocaleString('en-US',{month:'short',day:'numeric',year:'numeric'}):'Date pending';const money=(n:any)=>n?'$'+Number(n).toLocaleString():'—';
export default function Dashboard(){const[rows,setRows]=useState<A[]>([]),[checks,setChecks]=useState<A[]>([]),[loading,setLoading]=useState(true),[scanning,setScanning]=useState(false),[msg,setMsg]=useState(''),[q,setQ]=useState('');
async function load(){setLoading(true);try{const r=await fetch('/api/dashboard',{cache:'no-store'}),j=await r.json();setRows(j.auctions||[]);setChecks(j.checks||[]);if(j.error)setMsg(j.error)}finally{setLoading(false)}}useEffect(()=>{load()},[]);
async function scan(){setScanning(true);setMsg('Scanning Delaware CivilView…');try{const r=await fetch('/api/scan-auctions',{method:'POST'}),j=await r.json();if(!r.ok)throw Error(j.error);setMsg(`Scan complete: ${j.found} listings · ${j.newProperties} new properties${j.errors?.length?' · '+j.errors.join(' | '):''}`);await load()}catch(e:any){setMsg(e.message)}finally{setScanning(false)}}
const f=useMemo(()=>rows.filter(r=>`${r.properties?.address} ${r.properties?.parcel_number} ${r.sheriff_number} ${r.plaintiff} ${r.defendant}`.toLowerCase().includes(q.toLowerCase())),[rows,q]);const unresolved=checks.filter(x=>!['verified','not_found'].includes(x.status)).length;
return <main><Nav/><section className="content"><header><div><p className="eyebrow">DELAWARE / AUCTION RADAR</p><h1>Investment Command Center</h1><p className="subtitle">Auction discovery, evidence-driven due diligence and transparent bid ceilings.</p></div><div className="headerActions"><button className="iconBtn"><Bell size={18}/></button><button className="primary" onClick={scan} disabled={scanning}><RefreshCw size={17} className={scanning?'spin':''}/>{scanning?'Scanning…':'Scan Auctions'}</button></div></header>
<div className="search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search address, parcel, owner, plaintiff or sheriff number..."/><button onClick={scan}>Refresh</button></div>{msg&&<div className="scanMessage">{msg}</div>}
<div className="stats"><div className="stat"><span>Tracked auctions</span><strong>{rows.length}</strong><small>{loading?'Loading…':'Supabase live data'}</small></div><div className="stat"><span>Counties</span><strong>{new Set(rows.map(r=>r.properties?.county).filter(Boolean)).size}/3</strong><small className="good">Delaware coverage</small></div><div className="stat"><span>Due diligence checks</span><strong>{checks.length}</strong><small>Evidence status tracked</small></div><div className="stat"><span>Unresolved flags</span><strong>{unresolved}</strong><small className="warn">Review before bidding</small></div></div>
<div className="sectionHead"><div><h2>Auction feed</h2><p>CivilView is discovery evidence, not a clean-title conclusion.</p></div><button className="secondary" onClick={scan}><TrendingUp size={16}/> Refresh feed</button></div>
<div className="grid">{f.map(r=>{const p=r.properties||{};return <div className="propertyCard" key={r.id}><div className="cardTop"><span className="pill medium">{(r.status||'scheduled').toUpperCase()}</span><span className="county">{p.county}</span></div><h3>{p.address}</h3><p className="muted"><MapPin size={14}/>{p.city||'Delaware'}, DE</p><div className="metrics"><div><span>Sheriff #</span><b>{r.sheriff_number||'—'}</b></div><div><span>Parcel</span><b>{p.parcel_number||'Not listed'}</b></div><div><span>Upset / opening</span><b className="accent">{money(r.upset_price||r.opening_bid)}</b></div></div><div className="risk"><TriangleAlert size={16}/><span>Title status: not presumed · {r.occupancy_status||'occupancy unverified'}</span></div><div className="cardFoot"><span><CalendarDays size={15}/>{fmt(r.sale_date)}</span><a href={`/property/${p.id}`}><ShieldCheck size={13}/> Investigate</a>{r.source_url&&<a href={r.source_url} target="_blank" rel="noreferrer">Source <ExternalLink size={13}/></a>}</div></div>})}</div>
{!loading&&!f.length&&<div className="notice"><TriangleAlert/><div><b>No auction records stored.</b><p>Press Scan Auctions to populate the database.</p></div></div>}</section></main>}
