'use client';import {useEffect,useState} from 'react';import Nav from './Nav';import {ArrowLeft,ExternalLink,Play,ShieldAlert,Calculator,FileSearch,Landmark,Scale,Home,Save} from 'lucide-react';
const money=(x:any)=>x==null?'—':'$'+Number(x).toLocaleString(undefined,{maximumFractionDigits:0});const labels:any={county_property:'County property',deed_chain:'Deed chain',mortgages:'Mortgages',assignments_releases:'Assignments / releases',judgments:'Judgments',state_tax_liens:'State tax liens',federal_tax_liens:'Federal tax liens',municipal_tax_water_sewer:'Taxes / water / sewer',hoa_condo:'HOA / condo',bankruptcy:'Bankruptcy',occupancy:'Occupancy',valuation:'Valuation',comparables:'Comparables',flood_risk:'Flood risk (FEMA)'};
export default function Workspace({id}:{id:string}){const[d,setD]=useState<any>(null),[msg,setMsg]=useState(''),[form,setForm]=useState<any>({arv:0,repairs:0,taxes:0,surviving_liens:0,closing_and_carry:0,risk_reserve:0,desired_profit:0,acquisition_costs:0,financing_costs:0});
async function load(){const r=await fetch(`/api/property/${id}`,{cache:'no-store'});setD(await r.json())}useEffect(()=>{load()},[]);
async function dd(){setMsg('Running complete FREE-ONLY research…');try{const r=await fetch(`/api/property/${id}/due-diligence`,{method:'POST'}),t=await r.text();let j:any;try{j=JSON.parse(t)}catch{throw new Error(`Server response ${r.status}: ${t.replace(/<[^>]*>/g,' ').slice(0,160)}`)}if(!r.ok||!j.ok)throw new Error(j.error||'Research failed');setMsg(`FREE research complete · ${j.publicSourcesReached||0} public sources reached · Census ${j.geocoded?'✓':'—'} · FEMA ${j.femaQueried?'✓':'—'}`)}catch(e:any){setMsg(`Research error: ${e.message}`)}await load()}
async function bid(){const r=await fetch('/api/bid-model',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...form,property_id:id})}),j=await r.json();setMsg(j.ok?`Maximum bid model saved: ${money(j.model.max_bid)}`:j.error);await load()}
if(!d)return <main><Nav/><section className="content"><p>Loading property workspace…</p></section></main>;if(d.error)return <main><Nav/><section className="content"><p>{d.error}</p></section></main>;const p=d.property,a=d.auctions?.[0],checks=d.checks||[],bm=d.bidModel;
return <main><Nav/><section className="content"><a className="back" href="/"><ArrowLeft size={16}/> Dashboard</a><header><div><p className="eyebrow">{p.county} / PROPERTY WORKSPACE</p><h1>{p.address}</h1><p className="subtitle">Parcel {p.parcel_number||'not listed'} · Owner/defendant {p.owner_name||a?.defendant||'unverified'}</p></div><button className="primary" onClick={dd}><Play size={17}/> Run Due Diligence</button></header>{msg&&<div className="scanMessage">{msg}</div>}
<div className="stats"><div className="stat"><span>Sale date</span><strong className="smallStrong">{a?.sale_date?new Date(a.sale_date).toLocaleDateString():'Pending'}</strong><small>{a?.status||'unknown'}</small></div><div className="stat"><span>Upset/opening</span><strong>{money(a?.upset_price||a?.opening_bid)}</strong><small>From auction source when available</small></div><div className="stat"><span>Latest max bid</span><strong>{money(bm?.max_bid)}</strong><small>Transparent investor model</small></div><div className="stat"><span>Verified checks</span><strong>{checks.filter((x:any)=>x.status==='verified').length}/{checks.length}</strong><small className="warn">Missing ≠ clear</small></div></div>
<div className="workspaceGrid"><section className="panel"><h2><FileSearch size={19}/> Due diligence</h2><p className="panelSub">Every conclusion must have evidence. “Not found” only means a source was actually checked.</p><div className="checklist">{Object.keys(labels).map(k=>{const x=checks.find((c:any)=>c.check_type===k);return <div className="checkRow" key={k}><div><b>{labels[k]}</b><small>{x?.source||'Not checked'}</small>{x?.result?.sources?.map((s:any)=><a key={s.url} href={s.url} target="_blank" rel="noreferrer" className="miniSource">Open official source ↗</a>)}</div><span className={`status ${x?.status||'pending'}`}>{(x?.status||'PENDING').replaceAll('_',' ')}</span></div>})}</div></section>
<section className="panel"><h2><Landmark size={19}/> Title & liens</h2><p className="panelSub">Recorded amount is not assumed to equal payoff balance.</p>{d.encumbrances?.length?d.encumbrances.map((e:any)=><div className="evidence" key={e.id}><b>{e.kind}</b><span>{e.creditor||'Unknown creditor'} · recorded {money(e.original_amount)}</span><small>{e.status} · priority {e.priority_rank||'unresolved'}</small></div>):<div className="empty">No verified encumbrances stored yet.</div>}<h3>Evidence / documents</h3>{p.free_research_summary&&<div className="empty"><b>FREE research summary</b><br/>Public sources reached: {p.free_research_summary.publicSourcesReached??0} · Geocoded: {p.free_research_summary.geocoded?'yes':'no'} · FEMA: {p.free_research_summary.femaQueried?'queried':'pending'}</div>}{d.sources?.slice(0,8).map((s:any)=><a className="sourceRow" key={s.id} href={s.source_url||'#'} target="_blank"><span>{s.provider} · {s.source_type}</span><ExternalLink size={14}/></a>)}{d.documents?.map((doc:any)=><a className="sourceRow" key={doc.id} href={doc.url||'#'} target="_blank"><span>PDF / document · {doc.title}</span><ExternalLink size={14}/></a>)}</section></div>
<section className="panel bidPanel"><h2><Calculator size={19}/> Bid Calculator</h2><p className="panelSub">Formula: ARV minus every entered cost, reserve and desired profit. No hidden AI score.</p><div className="formGrid">{Object.keys(form).map(k=><label key={k}>{k.replaceAll('_',' ')}<input type="number" value={form[k]} onChange={e=>setForm({...form,[k]:Number(e.target.value)})}/></label>)}</div><button className="primary" onClick={bid}><Save size={16}/> Calculate & save max bid</button>{bm&&<div className="maxBid">Current modeled ceiling <strong>{money(bm.max_bid)}</strong></div>}</section>
<section className="notice"><ShieldAlert/><div><b>Manual/professional verification remains part of the workflow.</b><p>CourtConnect, county recorder documents, municipal balances and title priority can require manual review or paid provider access. The app marks those checks unresolved instead of guessing.</p></div></section></section></main>}
