export type ResearchSource={key:string;label:string;kind:string;counties?:string[];url:string;automated:boolean;free:boolean;note:string};
export const RESEARCH_SOURCES:ResearchSource[]=[
{key:'ncc_property',label:'New Castle County Parcel Search',kind:'county_property',counties:['New Castle'],url:'https://www3.newcastlede.gov/parcel/search/',automated:true,free:true,note:'Official county parcel/property source.'},
{key:'ncc_recorder',label:'New Castle County Recorder Document Search',kind:'deed_chain',counties:['New Castle'],url:'https://www.newcastlede.gov/144/Document-Search',automated:true,free:true,note:'Official recorder entry/index. Paid images are never fetched.'},
{key:'kent_property',label:'Kent County Property Records',kind:'county_property',counties:['Kent'],url:'https://propertyrecords.kentcountyde.gov/',automated:true,free:true,note:'Official county property records.'},
{key:'kent_deeds',label:'Kent County Deeds Search',kind:'deed_chain',counties:['Kent'],url:'https://i2g.uslandrecords.com/DE/Kent2/D/Default.aspx',automated:true,free:true,note:'Official Kent land records entry.'},
{key:'sussex_property',label:'Sussex County Property Search',kind:'county_property',counties:['Sussex'],url:'https://property.sussexcountyde.gov/PT/forms/htmlframe.aspx?mode=content%2Fhome.htm',automated:true,free:true,note:'Official county assessment/tax property database.'},
{key:'sussex_deeds',label:'Sussex County Landmark',kind:'deed_chain',counties:['Sussex'],url:'https://deeds.sussexcountyde.gov/LandmarkWeb/Home/Index',automated:true,free:true,note:'Official recorder index supports parcel/name/instrument searches; subscription/image limits remain manual.'},
{key:'courtconnect',label:'Delaware CourtConnect',kind:'judgments',url:'https://courtconnect.courts.delaware.gov/cc/cconnect/ck_public_qry_main.cp_main_srch_options',automated:true,free:true,note:'Public civil case/judgment source; CourtConnect itself is not an official certified docket.'},
{key:'fema',label:'FEMA National Flood Hazard Layer',kind:'flood_risk',url:'https://hazards.fema.gov/femaportal/wps/portal/NFHLWMS',automated:true,free:true,note:'Federal public flood-risk source.'}
];