export type ResearchSource={key:string;label:string;kind:string;counties?:string[];url:string;automated:boolean;free:boolean;note:string};
export const RESEARCH_SOURCES:ResearchSource[]=[
{key:'ncc_property',label:'New Castle County Parcel Search',kind:'county_property',counties:['New Castle'],url:'https://www3.newcastlede.gov/parcel/search/',automated:false,free:true,note:'Official parcel/property source. Free public lookup; interactive verification.'},
{key:'ncc_recorder',label:'New Castle County Recorder Document Search',kind:'deed_chain',counties:['New Castle'],url:'https://www.newcastlede.gov/144/Document-Search',automated:false,free:true,note:'Official recorder entry point. Search/index access is used for verification; document-copy availability can vary.'},
{key:'kent_deeds',label:'Kent County Deeds Search',kind:'deed_chain',counties:['Kent'],url:'https://i2g.uslandrecords.com/DE/Kent2/D/Default.aspx',automated:false,free:true,note:'Official Kent land records. County guidance states document viewing is free.'},
{key:'kent_property',label:'Kent County Property Records',kind:'county_property',counties:['Kent'],url:'https://propertyrecords.kentcountyde.gov/',automated:false,free:true,note:'Official property records.'},
{key:'sussex_property',label:'Sussex County Property Search',kind:'county_property',counties:['Sussex'],url:'https://property.sussexcountyde.gov/PT/forms/htmlframe.aspx?mode=content%2Fhome.htm',automated:false,free:true,note:'Official assessment/tax property database; public search by owner/address.'},
{key:'sussex_deeds',label:'Sussex County Landmark',kind:'deed_chain',counties:['Sussex'],url:'https://deeds.sussexcountyde.gov/LandmarkWeb/Home/Index',automated:false,free:true,note:'Official recorder index/search. Some image/order features may have account/fee constraints.'},
{key:'courtconnect',label:'Delaware CourtConnect',kind:'judgments',url:'https://courtconnect.courts.delaware.gov/cc/cconnect/ck_public_qry_main.cp_main_srch_options',automated:false,free:true,note:'Official public civil case and judgment search. Results are evidence leads, not an official title certification.'}
];
