create extension if not exists pgcrypto;
create table if not exists public.properties (id uuid primary key default gen_random_uuid(), address text not null, city text, county text check (county in ('New Castle','Kent','Sussex')), state text not null default 'DE', parcel_number text, owner_name text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.auctions (id uuid primary key default gen_random_uuid(), property_id uuid not null references public.properties(id) on delete cascade, source text not null, sheriff_number text, sale_date timestamptz, opening_bid numeric(14,2), plaintiff text, defendant text, status text default 'scheduled', source_url text, retrieved_at timestamptz default now());
create table if not exists public.encumbrances (id uuid primary key default gen_random_uuid(), property_id uuid not null references public.properties(id) on delete cascade, kind text not null, creditor text, original_amount numeric(14,2), estimated_balance numeric(14,2), recording_date date, instrument_number text, priority_rank integer, status text default 'unverified', source_id uuid, notes text, created_at timestamptz default now());
create table if not exists public.valuations (id uuid primary key default gen_random_uuid(), property_id uuid not null references public.properties(id) on delete cascade, source text not null, value numeric(14,2), valuation_type text, as_of date, raw jsonb default '{}'::jsonb, created_at timestamptz default now());
create table if not exists public.due_diligence_checks (id uuid primary key default gen_random_uuid(), property_id uuid not null references public.properties(id) on delete cascade, check_type text not null, status text not null default 'pending', result jsonb default '{}'::jsonb, source text, checked_at timestamptz, created_at timestamptz default now());
create table if not exists public.sources (id uuid primary key default gen_random_uuid(), property_id uuid references public.properties(id) on delete cascade, provider text not null, source_type text not null, source_url text, external_reference text, retrieved_at timestamptz default now(), payload jsonb default '{}'::jsonb, verification_status text default 'unverified');
create table if not exists public.bid_models (id uuid primary key default gen_random_uuid(), property_id uuid not null references public.properties(id) on delete cascade, arv numeric(14,2), repairs numeric(14,2) default 0, taxes numeric(14,2) default 0, surviving_liens numeric(14,2) default 0, closing_and_carry numeric(14,2) default 0, risk_reserve numeric(14,2) default 0, target_factor numeric(5,4) default .72, max_bid numeric(14,2), created_at timestamptz default now());
alter table public.properties enable row level security;alter table public.auctions enable row level security;alter table public.encumbrances enable row level security;alter table public.valuations enable row level security;alter table public.due_diligence_checks enable row level security;alter table public.sources enable row level security;alter table public.bid_models enable row level security;
-- No public policies are created intentionally. Add authenticated-user policies when Auth is enabled.
create index if not exists properties_parcel_idx on public.properties(parcel_number);create index if not exists auctions_sale_date_idx on public.auctions(sale_date);create index if not exists encumbrances_property_idx on public.encumbrances(property_id);create index if not exists sources_property_idx on public.sources(property_id);
